server:
  port: 8761
eureka:
  instance:
    hostname: 111.230.99.118
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://47.111.99.118:8761/eureka/
  server:
    # https://www.jianshu.com/p/282137f07827
    # 主动失效时间
    eviction-interval-timer-in-ms: 5000
    # 禁用自我保护
    enableSelfPreservation: false
    # 禁用readOnlyCacheMap
    use-read-only-response-cache: false
spring:
  profiles:
    active: prod