server:
  port: 8761
eureka:
  instance:
    hostname: 111.230.143.197
  client:
    serviceUrl:
      defaultZone: http://111.230.143.197/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    # https://www.jianshu.com/p/282137f07827
    # 主动失效时间
    eviction-interval-timer-in-ms: 5000
    # 禁用自我保护
    enableSelfPreservation: false
    # 禁用readOnlyCacheMap
    use-read-only-response-cache: false
spring:
  profiles:
    active: prod